name: Automatic test for Linux

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Debian test
        run: ./tests/linux.sh debian:buster-slim
      - name: Ubuntu test
        run: ./tests/linux.sh ubuntu:focal
      - name: CentOS test
        run: ./tests/linux.sh centos:7
